language: python
dist: xenial
python:
  - 3.7
services:
  # MySQL 5.7 is the default on the Xenial 
  - mysql
env:
  - FLASK_ENV=testing FLASK_DEV_LINT_LOWEST_SCORE=6.0

stages:
  - test
  - code_audit

install:
  - pip install -r requirements.txt
  - pipenv --version
  - pipenv install --dev
  - cp .env.sample .env

jobs:
  include:
    - stage: test
      script:
        - flask create-db
        - flask db upgrade
        - flask routes
        - flask test
        # run integration tests
        - python -m unittest tests/skip_test_liveserver.py

    - stage: code_audit
      script:
        - flask dev
        - flask dev lint --lowest-score=$FLASK_DEV_LINT_LOWEST_SCORE
        - flask dev format
        - flask dev security_audit
        # - pipenv check
        - flask dev license_compliance_audit
