"""add user

Revision ID: 983e41e9b752
Revises: 
Create Date: 2020-09-10 14:20:07.014072

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '983e41e9b752'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
  # ### commands auto generated by Alembic - please adjust! ###
  op.create_table('users', sa.Column('id', sa.String(length=80),
                                     nullable=False),
                  sa.Column('first_name', sa.String(length=50), nullable=False),
                  sa.Column('last_name', sa.String(length=50), nullable=False),
                  sa.Column('username', sa.String(length=100), nullable=True),
                  sa.PrimaryKeyConstraint('id'),
                  sa.UniqueConstraint('username'))
  # ### end Alembic commands ###


def downgrade():
  # ### commands auto generated by Alembic - please adjust! ###
  op.drop_table('users')
  # ### end Alembic commands ###
